# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.3

env:
  - JULIA_VERSION=v1.3.0                                   # entry straight in Versions.toml
  - JULIA_VERSION=nightly                                  # entry from Builds.toml
  - JULIA_VERSION=58803fe7d3cc7303a9f50266971131913b4d2945 # directly from Git, never built
  - JULIA_VERSION=master                                   # directly from Git, likely built

branches:
  only:
  - master

notifications:
  email: false
