# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.3
  - 1.4
  - 1.5

env:
  global:
    - JULIA_DEBUG=NewPkgEval
  jobs:
    - JULIA_VERSION=v1.5.0                                   # entry straight in Versions.toml
    - JULIA_VERSION=nightly                                  # entry from Builds.toml
    - JULIA_VERSION=8cb458c6dcd8e067a3bd430b006efb0dfde56cf9 # directly from Git, never built
    - JULIA_VERSION=master                                   # directly from Git, likely built

branches:
  only:
  - master

notifications:
  email: false
