# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.3

env:
  - JULIA_VERSION=v1.3.0-rc5
  - JULIA_VERSION=master

branches:
  only:
  - master

notifications:
  email: false

