# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.3

env:
  - JULIA_VERSION=v1.3.0      # entry straight in Versions.toml
  - JULIA_VERSION=nightly     # entry from Builds.toml
  - JULIA_VERSION=master      # directly from Git

branches:
  only:
  - master

notifications:
  email: false
