["General"]
url = "https://github.com/JuliaRegistries/General.git"
uuid = "23338594-aafe-5451-b93e-139f81909106"
skip = [
    "julia", # really crappy software
    "AbstractAlgebra", # Hangs forever
    "DiscretePredictors", # Hangs forever
    "LinearLeastSquares", # Hangs forever
    "SLEEF", # Hangs forever
    "OrthogonalPolynomials", # Hangs forever
    "IndexableBitVectors",
    "LatinHypercubeSampling", # Hangs forever
    "DynamicalBilliards", # Hangs forever
    "ChangePrecision", # Hangs forever
    "Rectangle", # Hangs forever
    "Parts", # Hangs forever
    "ZippedArrays", # Hangs forever
    "Chunks", # Hangs forever
    "Electron",
    "DotOverloading",
    "ValuedTuples",
    "HCubature",
    "SequentialMonteCarlo",
    "RequirementVersions",
    "NumberedLines",
    "LazyContext",
    "RecurUnroll", # deleted, hangs
    "TypedBools", # deleted, hangs
    "LazyCall", # deleted, hangs
    "MeshCatMechanisms",
    "SessionHacker",
    "Embeddings",
    "GeoStatsDevTools",
    "DataDeps", # hangs
    "DataDepsGenerators", # hangs
    "MackeyGlass", # deleted, hangs
    "Keys", #deleted, hangs
]
