["General"]
url = "https://github.com/JuliaRegistries/General.git"
uuid = "23338594-aafe-5451-b93e-139f81909106"
skip = [
    "julia",
]
retry = [
    "EcologicalNetworks",
    "FixedEffectModels",
    "GLM",
    "SpatialJackknife",
    "StatsModels",
    "UncertainData",
    "StressTest",
    "StateSpaceReconstruction",
    "PolyChaos",
    "RoME",
]
